name: XfLoops' Blog
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi:      false
safe:     false
permalink: pretty
markdown: kramdown
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
paginate: 20
gems: [jekyll-paginate]
paginate_path: "page:num"